#!/bin/sh

# Note to Windows users: This is not actually platform specific.
mkdir -p src/include
"/usr/local/bin/R" --vanilla --slave --file=tools/make_cpp.R
cat src/*.cc > src/Modules.cpp
rm src/*.cc
"/usr/local/bin/R" --vanilla --slave -e 'roxygen2::roxygenize(clean = TRUE)'
exit $?



